micronaut:
  application:
    name: global-dashboard-db
  server:
    port: 8081 # Using 8081 to avoid conflict with potential other services on 8080

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/globaldashboard`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      clean-disabled: true

netty:
  default:
    allocator:
      max-order: 3
