micronaut:
  application:
    name: global-dashboard-db
  
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/global_dashboard
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      interceptor:
        classes: com.globaldashboard.db.infrastructure.kafka.MdcPropagationInterceptor
  consumers:
    auto-offset-reset: earliest
  topics:
    users: persistence.users
    dashboards: persistence.dashboards
    users-events: persistence.users.events
    dashboards-events: persistence.dashboards.events
